language: ruby
rvm:
  - 1.9.3
cache: bundler
gemfile:
  - gemfiles/Gemfile-travis
env:
  - DB=postgresql
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
notifications:  
  email: false